<x-layouts.app :title="$service->exists ? 'Editar servicio' : 'Nuevo servicio'">
    @php
        $savedPrices = $service->prices ?? collect();
        $priceRows = old('price_names') !== null
            ? collect(old('price_names'))->map(fn ($name, $index) => ['name' => $name, 'cost' => old('price_costs.'.$index), 'sale' => old('price_sales.'.$index)])
            : $savedPrices->map(fn ($price) => ['name' => $price->tier, 'cost' => $price->cost, 'sale' => $price->sale_price]);
        $priceRows = $priceRows->isNotEmpty() ? $priceRows : collect([['name' => '', 'cost' => '', 'sale' => '']]);
    @endphp
    <section class="page-title"><div><p class="eyebrow">CATÁLOGO · SERVICIOS</p><h1>{{ $service->exists ? 'Editar servicio' : 'Nuevo servicio' }}</h1><p>Define la información, precios y operación del servicio.</p></div><a class="button button-secondary" href="{{ route('services.index') }}">Cancelar</a></section>
    <form class="surface detail-form" method="POST" enctype="multipart/form-data" action="{{ $service->exists ? route('services.update', $service) : route('services.store') }}">@csrf @if($service->exists) @method('PUT') @endif
        <div class="form-section"><h2>Detalles del servicio</h2><div class="field-grid">
            <label><span>Nombre</span><input name="name" value="{{ old('name', $service->name) }}" required></label>
            <label><span>Categoría</span><select name="service_category_id" required><option value="">Seleccionar categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('service_category_id', $service->service_category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label>
            <label class="full-field"><span>Imagen de portada del servicio</span><span class="service-upload-box"><span class="service-upload-icon">↑</span><span><strong>Subir imagen</strong><small>Haz clic para elegir una imagen desde tu dispositivo</small></span><span class="service-upload-name" id="cover-image-name">Ningún archivo seleccionado</span><input id="cover-image" type="file" name="cover_image" accept="image/*"></span><small>Formatos permitidos: JPG, PNG o WebP · Máximo 5 MB.</small>@if($service->cover_image_path)<img class="service-cover-preview" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($service->cover_image_path) }}" alt="Imagen de {{ $service->name }}">@endif</label>
            <label class="full-field"><span>Descripción</span><textarea name="description" rows="4" placeholder="Descripción para el equipo…">{{ old('description', $service->description) }}</textarea></label>
            <label><span>Duración promedio (minutos)</span><input type="number" name="estimated_duration_minutes" min="5" max="720" value="{{ old('estimated_duration_minutes', $service->estimated_duration_minutes ?: 60) }}" required></label>
        </div></div>
        <div class="form-section"><div class="section-heading"><div><h2>Tabla de precios</h2><p>Agrega las tarifas que el equipo podrá elegir en el ticket.</p></div><label class="inline-field"><span>Tipo de precio</span><select name="price_type" id="price-type"><option value="fixed" @selected(old('price_type', $service->price_type ?: 'fixed') === 'fixed')>Fijo</option><option value="variable" @selected(old('price_type', $service->price_type) === 'variable')>Variable</option></select></label></div>
            <div id="fixed-prices" @if(old('price_type', $service->price_type ?: 'fixed') !== 'fixed') hidden @endif><div class="service-price-table-header"><span>Nombre del precio</span><span>Costo</span><span>Precio de venta</span><span>Utilidad</span><span></span></div><div id="price-rows">@foreach($priceRows as $row)<div class="service-price-row"><input name="price_names[]" value="{{ $row['name'] }}" placeholder="Ej. Regular" required><input name="price_costs[]" type="number" min="0" step=".01" value="{{ $row['cost'] }}" placeholder="$0.00"><input name="price_sales[]" class="price-sale" type="number" min="0" step=".01" value="{{ $row['sale'] }}" placeholder="$0.00" required><output class="price-profit">${{ number_format((float) $row['sale'] - (float) ($row['cost'] ?: 0), 2) }}</output><button type="button" class="button button-secondary remove-price" aria-label="Quitar precio">×</button></div>@endforeach</div><button type="button" class="button button-secondary" id="add-price">+ Agregar precio</button></div>
            <p class="form-help" id="variable-help" @if(old('price_type', $service->price_type ?: 'fixed') === 'fixed') hidden @endif>El precio se define al momento de agregar el servicio al ticket.</p>
        </div>
        <div class="form-section"><h2>Operación</h2><div class="field-grid"><label><span>Comisión del servicio (%)</span><input type="number" step=".01" min="0" max="100" name="commission_rate" value="{{ old('commission_rate', $service->commission_rate) }}"></label><label><span>Estatus</span><select name="status"><option value="active" @selected(old('status', $service->status ?: 'active') === 'active')>Activo</option><option value="inactive" @selected(old('status', $service->status) === 'inactive')>Inactivo</option></select></label><label class="switch-field"><input type="checkbox" name="requires_color_bar" value="1" @checked(old('requires_color_bar', $service->requires_color_bar))><span>Requiere Color Bar</span></label></div></div>
        <footer class="form-footer">@if($service->exists)<button class="button button-secondary" type="submit" form="deactivate-service">Desactivar</button>@endif<a href="{{ route('services.index') }}">Cancelar</a><button class="button button-primary" type="submit">Guardar servicio</button></footer>
    </form>
    @if($service->exists)<form id="deactivate-service" method="POST" action="{{ route('services.destroy', $service) }}" onsubmit="return confirm('¿Desactivar este servicio? Los tickets históricos no cambiarán.')">@csrf @method('DELETE')</form>@endif
    <script>
        (() => {
            const type = document.getElementById('price-type'); const fixed = document.getElementById('fixed-prices'); const help = document.getElementById('variable-help'); const rows = document.getElementById('price-rows'); const coverImage = document.getElementById('cover-image'); const coverImageName = document.getElementById('cover-image-name');
            const update = () => { const isFixed = type.value === 'fixed'; fixed.hidden = !isFixed; help.hidden = isFixed; rows.querySelectorAll('input').forEach((input) => { input.disabled = !isFixed; input.required = isFixed && input.name !== 'price_costs[]'; }); };
            const updateProfit = (row) => { const cost = parseFloat(row.querySelector('[name="price_costs[]"]').value) || 0; const sale = parseFloat(row.querySelector('[name="price_sales[]"]').value) || 0; row.querySelector('.price-profit').textContent = `$${(sale - cost).toFixed(2)}`; };
            rows.addEventListener('input', (event) => { const row = event.target.closest('.service-price-row'); if (row) updateProfit(row); }); rows.addEventListener('click', (event) => { if (event.target.closest('.remove-price') && rows.children.length > 1) event.target.closest('.service-price-row').remove(); });
            document.getElementById('add-price').addEventListener('click', () => { const row = document.createElement('div'); row.className = 'service-price-row'; row.innerHTML = '<input name="price_names[]" placeholder="Ej. Regular" required><input name="price_costs[]" type="number" min="0" step=".01" placeholder="$0.00"><input name="price_sales[]" type="number" min="0" step=".01" placeholder="$0.00" required><output class="price-profit">$0.00</output><button type="button" class="button button-secondary remove-price">×</button>'; rows.appendChild(row); });
            coverImage?.addEventListener('change', () => { coverImageName.textContent = coverImage.files[0]?.name || 'Ningún archivo seleccionado'; }); type.addEventListener('change', update); update();
        })();
    </script>
</x-layouts.app>
