<x-layouts.app title="Inventario">
<section class="page-title">
    <div><p class="eyebrow">INVENTARIO · {{ $locationModel?->name ?: 'TODAS LAS UBICACIONES' }}</p><h1>Existencias por ubicación</h1><p>El stock se controla por ubicación; Almacén abastece a Recepción y Color Bar.</p></div>
    <div class="title-actions">
        @if(in_array($location, ['REC', 'CB'], true))<a class="button button-primary" href="{{ route('inventory.requests.create', ['location' => $location]) }}">+ Solicitar inventario</a>@endif
        <a class="button button-secondary" href="{{ route('inventory.requests.index', $location ? ['location' => $location] : []) }}">Solicitudes</a>
        <a class="button button-secondary" href="{{ route('activity.index', $location ? ['location' => $location] : []) }}">Bitácoras</a>
    </div>
</section>
<section class="surface list-surface"><header class="list-controls"><form method="GET" class="list-filter-bar" aria-label="Filtros de inventario"><input type="hidden" name="location" value="{{ $location }}"><label class="list-search"><span>⌕</span><input name="search" value="{{ $search }}" placeholder="Producto, marca o SKU"></label><select name="category" aria-label="Filtrar por categoría"><option value="">Todas las categorías</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($categoryId === $category->id)>{{ $category->name }}</option>@endforeach</select><label class="check-filter"><input type="checkbox" name="low_stock" value="1" @checked($lowStock)> Bajo mínimo</label><button class="button button-secondary" type="submit">Filtrar</button>@if($search || $categoryId || $lowStock)<a class="filter-clear" href="{{ route('inventory.index', $location ? ['location' => $location] : []) }}">Limpiar</a>@endif</form><span class="record-count">{{ $balances->total() }} existencias</span></header><div class="data-table"><div class="table-head inventory-head"><span>PRODUCTO</span><span>UBICACIÓN</span><span>UNIDAD</span><span>EXISTENCIA</span><span>MÍN. / MÁX.</span></div>@forelse($balances as $balance)<div class="table-row inventory-row"><div><strong>{{ $balance->variant->product->name }}</strong><small>{{ $balance->variant->name }}</small></div><span>{{ $balance->location->name }}</span><span>{{ $balance->variant->base_unit }}</span><strong class="{{ (float) $balance->available_quantity <= (float) $balance->variant->minimum_stock ? 'inventory-low' : '' }}">{{ number_format((float)$balance->available_quantity,3) }}</strong><small>{{ number_format((float)$balance->variant->minimum_stock,0) }} / {{ number_format((float)$balance->variant->maximum_stock,0) }}</small></div>@empty<p class="empty-state">No hay existencias registradas con estos filtros.</p>@endforelse</div><div class="pagination-row">{{ $balances->links() }}</div></section>
</x-layouts.app>
