@php($title = ['administracion' => 'Administración', 'recepcion' => 'Recepción', 'color-bar' => 'Color Bar', 'almacen' => 'Almacén'][$mode])
<x-layouts.app :title="$title">
@if($mode === 'administracion')
<section class="page-title"><div><p class="eyebrow">RESUMEN DEL DÍA</p><h1>Buenos días, {{ str(auth()->user()->name)->before(' ') }}.</h1><p>Datos operativos actualizados de CREPÉ.</p></div><a class="button button-primary" href="{{ route('reports.index') }}">Ver reportes <span>→</span></a></section>
<section class="metric-grid"><article class="metric-card"><span>VENTAS HOY</span><strong>${{ number_format($salesToday, 0) }}</strong><small class="neutral">Total real de tickets del día</small></article><article class="metric-card"><span>TICKETS ABIERTOS</span><strong>{{ $tickets->count() }}</strong><small class="neutral">En operación o servicio</small></article><article class="metric-card"><span>CITAS HOY</span><strong>{{ $appointments->count() }}</strong><small class="neutral">Agenda confirmada</small></article><article class="metric-card"><span>STOCK BAJO</span><strong>{{ $lowStock->count() }}</strong><small class="neutral">Unidades bajo mínimo de referencia</small></article></section>
<section class="dashboard-grid"><article class="surface table-surface"><header><div><h2>Agenda de hoy</h2><p>{{ now()->translatedFormat('l, d \d\e F') }}</p></div><a href="{{ route('agenda.index') }}">Ver agenda →</a></header><div class="agenda-list">@forelse($appointments as $appointment)<a class="agenda-row" href="{{ $appointment->ticket ? route('tickets.show', $appointment->ticket) : route('agenda.index') }}"><time>{{ $appointment->starts_at->format('H:i') }}</time><div><strong>{{ $appointment->customer->full_name }}</strong><span>{{ $appointment->services->pluck('name_snapshot')->join(' + ') }} · {{ $appointment->employee->full_name }}</span></div><span class="pill {{ str($appointment->status)->slug('-') }}">{{ str($appointment->status)->headline() }}</span></a>@empty<p class="empty-state">No hay citas para hoy.</p>@endforelse</div></article><article class="surface stock-surface"><header><div><h2>Atención requerida</h2><p>Inventario y operación</p></div></header><div class="alert-list">@forelse($lowStock->take(3) as $balance)<a href="{{ route('inventory.index') }}"><span class="alert-mark">!</span><p><strong>{{ $balance->variant->product->name }} con stock bajo</strong><small>{{ $balance->location->name }} · {{ $balance->available_quantity }} {{ $balance->variant->base_unit }}</small></p><b>→</b></a>@empty<a href="{{ route('inventory.index') }}"><span class="alert-mark amber">✓</span><p><strong>Inventario en niveles saludables</strong><small>Ver existencias y movimientos</small></p><b>→</b></a>@endforelse</div></article></section>
@elseif($mode === 'recepcion')
<section class="page-title"><div><p class="eyebrow">OPERACIÓN DEL DÍA</p><h1>Recepción</h1><p>Encuentra una clienta, abre su ticket o crea una cita.</p></div><div class="title-actions"><button class="button button-secondary" type="button" data-dialog-open="day-availability">Disponibilidad del día</button><a class="button button-secondary" href="{{ route('customers.create') }}">+ Nueva clienta</a><a class="button button-secondary" href="{{ route('tickets.product-sales.create') }}">+ Venta de producto</a><a class="button button-primary" href="{{ route('appointments.create') }}">+ Nueva cita</a></div></section>
<section class="reception-toolbar"><form class="search-box" method="GET" action="{{ route('tickets.index') }}"><span>⌕</span><input name="search" value="{{ request('search') }}" placeholder="Buscar clienta o ticket..."><button type="submit">Buscar</button></form><div class="segmented"><a class="{{ !request('status') ? 'selected' : '' }}" href="{{ route('workspace', 'recepcion') }}">Todos</a><a href="{{ route('agenda.index') }}">Agenda</a><a href="{{ route('tickets.index', ['status' => 'in_service']) }}">En servicio</a><a href="{{ route('tickets.index', ['status' => 'open']) }}">Por cobrar</a></div></section>
<section class="ticket-grid">@forelse($tickets as $ticket)@php($ticketDisplayName = $ticket->customer?->full_name ?? 'Venta de mostrador')<a class="ticket-card" href="{{ route('tickets.show', $ticket) }}"><header><div class="customer-avatar">{{ str($ticket->customer?->first_name ?? 'V')->substr(0, 1) }}</div><span class="pill {{ $ticket->status === 'in_service' ? 'en-servicio' : 'confirmada' }}">{{ $ticket->status === 'in_service' ? 'En servicio' : 'Abierto' }}</span></header><h2>{{ $ticketDisplayName }}</h2>@if($ticket->ticket_type === 'product_sale')<p>Venta de producto</p>@else<p>{{ $ticket->appointment?->starts_at?->format('h:i A') ?: 'Sin cita' }} · {{ $ticket->appointment?->services?->pluck('name_snapshot')->join(' + ') ?: 'Venta en recepción' }}</p>@endif<div class="ticket-meta"><span>{{ $ticket->appointment?->employee?->full_name ?: 'Sin estilista asignada' }}</span><strong>Saldo ${{ number_format($ticket->balance, 0) }}</strong></div><span class="card-link">Abrir ticket <span>→</span></span></a>@empty<p class="empty-state">No hay tickets abiertos. <a href="{{ route('appointments.create') }}">Crear una cita</a></p>@endforelse</section>
<dialog class="availability-dialog" id="day-availability"><form method="dialog"><header><div><p class="eyebrow">RECEPCIÓN</p><h2>Disponibilidad del día</h2><p>Consulta los horarios libres de una estilista.</p></div><button class="dialog-close" type="button" data-dialog-close aria-label="Cerrar">×</button></header><div class="availability-filters"><label><span>Estilista</span><select id="availability-employee"><option value="">Selecciona una estilista</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>@endforeach</select></label><label><span>Fecha</span><input id="availability-date" type="date" value="{{ now()->toDateString() }}"></label><label><span>Duración</span><select id="availability-duration"><option value="30">30 min</option><option value="60" selected>1 hora</option><option value="90">1 h 30 min</option><option value="120">2 horas</option></select></label></div><div class="availability-results" id="availability-results"><p class="availability-empty">Selecciona una estilista para ver sus horarios disponibles.</p></div><footer><button class="button button-secondary" type="button" data-dialog-close>Cerrar</button></footer></form></dialog>
<script>
    (() => {
        const dialog = document.getElementById('day-availability');
        if (!dialog) return;
        const employee = document.getElementById('availability-employee');
        const date = document.getElementById('availability-date');
        const duration = document.getElementById('availability-duration');
        const results = document.getElementById('availability-results');
        const availabilityUrl = @json(route('appointments.availability'));
        const appointmentUrl = @json(route('appointments.create'));
        const render = async () => {
            if (!employee.value) {
                results.innerHTML = '<p class="availability-empty">Selecciona una estilista para ver sus horarios disponibles.</p>';
                return;
            }
            results.innerHTML = '<p class="availability-loading">Consultando horarios disponibles…</p>';
            const params = new URLSearchParams({ date: date.value, duration_minutes: duration.value, 'employee_ids[]': employee.value });
            try {
                const response = await fetch(`${availabilityUrl}?${params}`);
                const slots = response.ok ? (await response.json()).available : [];
                if (!slots.length) {
                    results.innerHTML = '<p class="availability-empty">No hay horarios disponibles para esta fecha y duración.</p>';
                    return;
                }
                results.innerHTML = `<p class="availability-summary">${slots.length} horarios disponibles · ${employee.options[employee.selectedIndex].text}</p><div class="availability-slots">${slots.map((slot) => `<a class="availability-slot" href="${appointmentUrl}?date=${encodeURIComponent(date.value)}&time=${encodeURIComponent(slot)}&employee_id=${encodeURIComponent(employee.value)}"><span>◷</span><strong>${slot}</strong><small>${slot} · ${duration.options[duration.selectedIndex].text}</small></a>`).join('')}</div>`;
            } catch {
                results.innerHTML = '<p class="availability-empty">No fue posible consultar la disponibilidad. Intenta de nuevo.</p>';
            }
        };
        document.querySelector('[data-dialog-open="day-availability"]')?.addEventListener('click', () => { dialog.showModal(); render(); });
        [employee, date, duration].forEach((field) => field.addEventListener('change', render));
        document.querySelectorAll('[data-dialog-close]').forEach((button) => button.addEventListener('click', () => button.closest('dialog')?.close()));
    })();
</script>
@elseif($mode === 'almacen')
<section class="page-title"><div><p class="eyebrow">CONTROL DE INVENTARIO</p><h1>Almacén</h1><p>Administra productos, existencias y movimientos para las áreas de CREPÉ.</p></div><div class="title-actions"><a class="button button-secondary" href="{{ route('inventory.index', ['location' => 'ALM']) }}">Ver inventario</a><a class="button button-primary" href="{{ route('products.create') }}">+ Dar de alta producto</a></div></section>
<section class="storage-module-grid"><a class="surface storage-module-card" href="{{ route('products.index') }}"><span class="module-icon">＋</span><div><strong>Productos</strong><small>Da de alta y actualiza productos y presentaciones.</small></div><span>→</span></a><a class="surface storage-module-card" href="{{ route('inventory.index', ['location' => 'ALM']) }}"><span class="module-icon">▦</span><div><strong>Existencias</strong><small>Consulta el inventario disponible en el almacén.</small></div><span>→</span></a><a class="surface storage-module-card" href="{{ route('activity.index', ['location' => 'ALM']) }}"><span class="module-icon">◷</span><div><strong>Bitácoras</strong><small>Consulta movimientos, traspasos y solicitudes cerradas.</small></div><span>→</span></a><a class="surface storage-module-card" href="{{ route('inventory.requests.index') }}"><span class="module-icon">⌁</span><div><strong>Solicitudes de inventario</strong><small>Autoriza entregas para Recepción y Color Bar, totales o parciales.</small></div><span>→</span></a></section>
@else
<section class="page-title"><div><p class="eyebrow">FORMULACIÓN Y CONSUMO</p><h1>Tickets activos</h1><p>Selecciona un ticket y registra consumos reales en gramos, mililitros o unidades.</p></div><a class="button button-secondary" href="{{ route('inventory.index', ['location' => 'CB']) }}">Inventario Color Bar</a></section>
<section class="color-layout"><div class="surface color-queue"><header><div><h2>Requieren Color Bar</h2><p>{{ $tickets->count() }} tickets activos</p></div><a class="mini-search" href="{{ route('color-bar.index') }}">Registrar fórmula →</a></header>@forelse($tickets as $ticket)<a class="color-ticket" href="{{ route('color-bar.index', ['ticket' => $ticket->id]) }}"><span class="customer-avatar">{{ str($ticket->customer->first_name)->substr(0, 1) }}</span><span><strong>{{ $ticket->customer->full_name }}</strong><small>{{ $ticket->appointment?->services?->pluck('name_snapshot')->join(' + ') ?: 'Ticket sin cita' }} · {{ $ticket->appointment?->employee?->full_name ?: 'Sin asignar' }}</small></span><time>{{ $ticket->appointment?->starts_at?->format('H:i') ?: '—' }}</time><b>→</b></a>@empty<p class="empty-state">No hay tickets activos para formular.</p>@endforelse</div><aside class="formula-preview"><div class="preview-icon">✦</div><h2>Registrar consumo</h2><p>Abre un ticket de la lista para ir directo al registro de fórmula y descontar el inventario real.</p><a class="button button-primary" href="{{ route('color-bar.index') }}">Ir a Color Bar</a></aside></section>
@endif
</x-layouts.app>
