@props(['title' => 'CREPÉ'])
@php($activeMode = session('crepe.mode', 'administracion'))
@php($modeTitle = ['administracion' => 'Administración', 'recepcion' => 'Recepción', 'color-bar' => 'Color Bar', 'almacen' => 'Almacén', 'finanzas' => 'Finanzas', 'promos' => 'Promos', 'configuracion' => 'Configuración'][$activeMode] ?? 'Administración')
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title }} · CREPÉ</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="app-body"><header class="app-nav"><a class="brand-lockup" href="{{ route('modes.select') }}"><x-brand-logo /></a><nav>
@if($activeMode === 'recepcion')
<a class="{{ request()->routeIs('workspace') && request()->route('mode') === 'recepcion' ? 'is-active' : '' }}" href="{{ route('workspace', 'recepcion') }}">Inicio</a><a class="{{ request()->routeIs('agenda.*', 'appointments.*') ? 'is-active' : '' }}" href="{{ route('agenda.index') }}">Agenda</a><a class="{{ request()->routeIs('tickets.*') ? 'is-active' : '' }}" href="{{ route('tickets.index') }}">Tickets</a><a class="{{ request()->routeIs('customers.*') ? 'is-active' : '' }}" href="{{ route('customers.index') }}">Clientas</a><a class="{{ request()->routeIs('inventory.*') ? 'is-active' : '' }}" href="{{ route('inventory.index', ['location' => 'REC']) }}">Inventario Recepción</a><a class="{{ request()->routeIs('activity.*') ? 'is-active' : '' }}" href="{{ route('activity.index', ['location' => 'REC']) }}">Bitácora</a><a class="nav-button nav-button-secondary" href="{{ route('inventory.requests.create', ['location' => 'REC']) }}">Solicitar inventario</a><a class="{{ request()->routeIs('cash.*') ? 'is-active' : '' }}" href="{{ route('cash.index') }}">Caja</a>
@elseif($activeMode === 'color-bar')
<a class="{{ request()->routeIs('color-bar.*') ? 'is-active' : '' }}" href="{{ route('color-bar.index') }}">Tickets</a><a class="{{ request()->routeIs('inventory.*') ? 'is-active' : '' }}" href="{{ route('inventory.index', ['location' => 'CB']) }}">Inventario Color Bar</a><a class="{{ request()->routeIs('activity.*') ? 'is-active' : '' }}" href="{{ route('activity.index', ['location' => 'CB']) }}">Bitácora</a><a class="nav-button nav-button-secondary" href="{{ route('inventory.requests.create', ['location' => 'CB']) }}">Solicitar inventario</a><a class="{{ request()->routeIs('tickets.*') ? 'is-active' : '' }}" href="{{ route('tickets.index') }}">Todos los tickets</a>
@elseif($activeMode === 'almacen')
<a class="{{ request()->routeIs('workspace') ? 'is-active' : '' }}" href="{{ route('workspace', 'almacen') }}">Inicio</a><a class="{{ request()->routeIs('products.*') ? 'is-active' : '' }}" href="{{ route('products.index') }}">Productos</a><a class="{{ request()->routeIs('inventory.index') && request('location') === 'ALM' ? 'is-active' : '' }}" href="{{ route('inventory.index', ['location' => 'ALM']) }}">Inventario</a><a class="{{ request()->routeIs('purchase-orders.*') ? 'is-active' : '' }}" href="{{ route('purchase-orders.index') }}">Órdenes de compra</a><a class="{{ request()->routeIs('activity.*') ? 'is-active' : '' }}" href="{{ route('activity.index', ['location' => 'ALM']) }}">Bitácoras</a><a class="nav-button nav-button-secondary" href="{{ route('inventory.index', ['location' => 'ALM']) }}">Ver inventario</a><a class="nav-button nav-button-secondary" href="{{ route('inventory.requests.index') }}">Solicitudes</a>
@elseif($activeMode === 'promos')
<a class="{{ request()->routeIs('promotions.*') ? 'is-active' : '' }}" href="{{ route('promotions.index') }}">Promos</a><a class="{{ request()->routeIs('tickets.*') ? 'is-active' : '' }}" href="{{ route('tickets.index') }}">Tickets</a>
@elseif($activeMode === 'configuracion')
<a class="{{ request()->routeIs('settings.*') ? 'is-active' : '' }}" href="{{ route('settings.edit') }}">Configuración</a>
@elseif($activeMode === 'finanzas')
<a class="{{ request()->query('view', 'dashboard') === 'dashboard' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'dashboard']) }}">Resumen</a><a class="{{ request()->query('view') === 'movements' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'movements']) }}">Movimientos</a><a class="{{ request()->routeIs('cash.*') ? 'is-active' : '' }}" href="{{ route('cash.index') }}">Cortes</a><a class="{{ request()->query('view') === 'accounts' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'accounts']) }}">Cuentas</a><a class="{{ request()->routeIs('payables.*') ? 'is-active' : '' }}" href="{{ route('payables.index') }}">CxP</a><a class="{{ request()->routeIs('payroll.*') ? 'is-active' : '' }}" href="{{ route('payroll.index') }}">Nómina</a><a class="{{ request()->query('view') === 'catalogs' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'catalogs']) }}">Catálogos</a>
@else
<a class="{{ request()->routeIs('workspace') && request()->route('mode') === 'administracion' ? 'is-active' : '' }}" href="{{ route('workspace', 'administracion') }}">Dashboard</a><a class="{{ request()->routeIs('customers.*') ? 'is-active' : '' }}" href="{{ route('customers.index') }}">Clientas</a><a class="{{ request()->routeIs('employees.*') ? 'is-active' : '' }}" href="{{ route('employees.index') }}">Equipo</a><a class="{{ request()->routeIs('services.*') ? 'is-active' : '' }}" href="{{ route('services.index') }}">Servicios</a><a class="{{ request()->routeIs('reports.*') ? 'is-active' : '' }}" href="{{ route('reports.index') }}">Reportes</a>
@endif
</nav><div class="nav-actions"><a class="mode-switcher" href="{{ route('modes.select') }}"><span class="status-dot"></span> {{ $modeTitle }} <span>⌄</span></a><div class="avatar">{{ str(auth()->user()->name)->substr(0, 1) }}</div></div></header><main class="workspace">@if(session('success'))<div class="notice-success">✓ {{ session('success') }}</div>@endif{{ $slot }}</main></body></html>
