<x-layouts.app title="Detalle de cuenta por pagar">
    <section class="page-heading">
        <div><p class="eyebrow">CUENTAS POR PAGAR · DETALLE</p><h1>{{ $invoice->purchaseOrder->supplier->name }}</h1><p>Factura {{ $invoice->invoice_reference ?: 'sin folio' }} · Orden {{ $invoice->purchaseOrder->code }}</p></div>
        <a class="button button-secondary" href="{{ route('payables.index') }}">Volver a CxP</a>
    </section>

    <section class="payable-detail-grid">
        <article class="surface payable-detail-main">
            <header><div><p class="eyebrow">CUENTA DEL PROVEEDOR</p><h2>Factura {{ $invoice->invoice_reference ?: 'Sin folio' }}</h2><p>Recibida {{ $invoice->purchaseOrder->received_at?->format('d/m/Y') ?? '—' }} · Vence {{ $invoice->due_on->format('d/m/Y') }}</p></div><span class="status-badge">{{ $invoice->status === 'paid' ? 'Pagada' : ($invoice->status === 'partial' ? 'Abono parcial' : 'Pendiente') }}</span></header>
            <div class="payable-detail-summary"><div><span>Importe</span><strong>&dollar;{{ number_format((float) $invoice->amount, 2) }}</strong></div><div><span>Pagado</span><strong>&dollar;{{ number_format((float) $invoice->paid_amount, 2) }}</strong></div><div class="payable-detail-balance"><span>Saldo pendiente</span><strong>&dollar;{{ number_format((float) $invoice->amount - (float) $invoice->paid_amount, 2) }}</strong></div></div>
            @if($invoice->invoice_path)<div class="payable-evidence-link"><span>Factura del proveedor</span><a href="{{ asset('storage/'.$invoice->invoice_path) }}" target="_blank" rel="noopener">Abrir comprobante ↗</a></div>@endif
            <div class="payable-payment-history payable-payment-history-table"><div class="payable-payment-history-heading"><strong>Historial de abonos</strong><span>{{ $invoice->payments->count() }} registrados</span></div>@forelse($invoice->payments as $payment)<div class="payable-payment-row"><span>{{ $payment->paid_on->format('d/m/Y') }}</span><span>{{ $payment->account?->name ?? 'Cuenta eliminada' }}</span><strong>&dollar;{{ number_format((float) $payment->amount, 2) }}</strong><span>{{ $payment->reference ?: 'Sin referencia' }}@if($payment->evidence_path) · <a href="{{ asset('storage/'.$payment->evidence_path) }}" target="_blank" rel="noopener">Comprobante ↗</a>@endif</span></div>@empty<p class="empty-state">Aún no hay abonos registrados.</p>@endforelse</div>
        </article>
        @if($invoice->status !== 'paid')
            <article class="surface payable-payment-panel"><header><div><p class="eyebrow">NUEVO MOVIMIENTO</p><h2>Registrar abono</h2><p>Agrega pagos parciales con fecha y evidencia hasta liquidar la factura.</p></div></header><form method="POST" action="{{ route('payables.payments.store', $invoice) }}" enctype="multipart/form-data" class="payable-payment-form">@csrf<label><span>Cuenta de origen</span><select name="finance_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></label><label><span>Importe del abono</span><input name="amount" type="number" min=".01" max="{{ (float) $invoice->amount - (float) $invoice->paid_amount }}" step=".01" required></label><label><span>Fecha del pago</span><input name="paid_on" type="date" value="{{ now()->toDateString() }}" required></label><label><span>Referencia <small>Opcional</small></span><input name="reference" maxlength="120" placeholder="Transferencia, folio, etc."></label><label><span>Notas <small>Opcional</small></span><textarea name="notes" rows="3" maxlength="1000" placeholder="Observación del pago"></textarea></label><label class="full-field"><span>Comprobante <small>Opcional · PDF o imagen</small></span><input name="evidence" type="file" accept="application/pdf,image/jpeg,image/png"></label><button class="button button-primary" type="submit">Registrar abono</button></form></article>
        @endif
    </section>
</x-layouts.app>
