<x-layouts.app title="Resumen financiero">
    @php
        $paymentTotals = $payments->groupBy('method')->map(fn ($rows) => (float) $rows->sum('amount'));
        $productPercent = $totalRevenue > 0 ? round($productRevenue / $totalRevenue * 100) : 0;
        $servicePercent = $totalRevenue > 0 ? 100 - $productPercent : 0;
        $expenseTotal = $expenses->sum('amount');
        $servicePalette = ['#b95070', '#d88ca4', '#8c6b9f', '#6b8fc4', '#4eaa8b', '#c7b07a'];
        $serviceOffset = 0;
        $serviceSegments = [];
        foreach ($serviceMix as $index => $serviceMixItem) {
            $nextOffset = min(100, $serviceOffset + $serviceMixItem['percent']);
            $serviceSegments[] = $servicePalette[$index % count($servicePalette)].' '.$serviceOffset.'% '.$nextOffset.'%';
            $serviceOffset = $nextOffset;
        }
    @endphp
    <section class="page-title"><div><p class="eyebrow">CONTROL FINANCIERO</p><h1>Resumen financiero</h1><p>Ventas, ingresos y operación del {{ $fromLabel }} al {{ $toLabel }}.</p></div><div class="title-actions"><a class="button button-secondary" href="{{ route('finance.index', ['view' => 'movements']) }}">Ver movimientos</a><a class="button button-primary" href="{{ route('finance.index', ['view' => 'movements', 'modal' => 'transaction']) }}">+ Agregar movimiento</a></div></section>
    <form method="GET" class="list-filter-bar" aria-label="Periodo del resumen"><input type="hidden" name="view" value="dashboard"><label><span>Desde</span><input name="from" type="date" value="{{ $from }}"></label><label><span>Hasta</span><input name="to" type="date" value="{{ $to }}"></label><button class="button button-secondary" type="submit">Actualizar</button><a class="filter-clear" href="{{ route('finance.index', ['view' => 'dashboard']) }}">Mes actual</a></form>
    <section class="metric-grid"><article class="metric-card"><span>VENTAS DEL PERIODO</span><strong>${{ number_format($totalRevenue, 2) }}</strong><small class="positive">Servicios + productos</small></article><article class="metric-card"><span>INGRESOS EN CAJA</span><strong class="positive">${{ number_format($payments->sum('amount'), 2) }}</strong><small class="neutral">Efectivo ${{ number_format($paymentTotals->get('cash', 0), 2) }} · Bancario ${{ number_format($paymentTotals->get('card', 0) + $paymentTotals->get('transfer', 0), 2) }}</small></article><article class="metric-card"><span>GASTOS</span><strong class="negative">${{ number_format($expenseTotal, 2) }}</strong><small class="neutral">{{ $expenses->count() }} categorías</small></article><article class="metric-card"><span>NETO OPERATIVO</span><strong class="{{ $totalRevenue - $expenseTotal >= 0 ? 'positive' : 'negative' }}">${{ number_format($totalRevenue - $expenseTotal, 2) }}</strong><small class="neutral">Antes de otros ajustes</small></article></section>

    <section class="dashboard-grid" style="margin-top:16px"><article class="surface"><header><div><p class="eyebrow">MEZCLA DE VENTAS</p><h2>¿De dónde vienen los ingresos?</h2><p>Distribución de ventas de servicios y productos.</p></div></header><div class="finance-chart-layout"><div style="width:150px;height:150px;border-radius:50%;background:conic-gradient(#b95070 {{ $servicePercent }}%,#d9b2c0 {{ $servicePercent }}% {{ $servicePercent + $productPercent }}%,#edf0f5 0)"></div><div style="display:grid;gap:12px"><div><strong style="color:#b95070">{{ $servicePercent }}%</strong> Servicios <small style="display:block;color:#8994a5">${{ number_format($serviceRevenue, 2) }}</small></div><div><strong style="color:#9b7890">{{ $productPercent }}%</strong> Productos <small style="display:block;color:#8994a5">${{ number_format($productRevenue, 2) }}</small></div></div></div></article><article class="surface"><header><div><p class="eyebrow">MÉTODOS DE COBRO</p><h2>Ingresos por cuenta de pago</h2><p>Pagos registrados en tickets.</p></div></header><div class="agenda-list"><div class="agenda-row"><time>Efectivo</time><div><strong>${{ number_format($paymentTotals->get('cash', 0), 2) }}</strong><span>{{ $payments->where('method', 'cash')->count() }} pagos</span></div></div><div class="agenda-row"><time>Bancario</time><div><strong>${{ number_format($paymentTotals->get('card', 0) + $paymentTotals->get('transfer', 0), 2) }}</strong><span>Tarjetas y transferencias</span></div></div><div class="agenda-row"><time>Gift Cards</time><div><strong>${{ number_format($paymentTotals->get('gift_card', 0), 2) }}</strong><span>Aplicadas en tickets</span></div></div><div class="agenda-row"><time>Otros</time><div><strong>${{ number_format($paymentTotals->get('other', 0), 2) }}</strong><span>Otros métodos</span></div></div></div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">PRODUCTOS MÁS VENDIDOS</p><h2>Top 10 productos</h2></div><a href="{{ route('products.index') }}">Catálogo →</a></header><div class="agenda-list">@forelse($products as $product)<div class="agenda-row"><time>{{ number_format($product['quantity'], 0) }} u.</time><div><strong>{{ $product['name'] }}</strong><span>${{ number_format($product['amount'], 2) }}</span></div></div>@empty<p class="empty-state">No hay ventas de productos en este periodo.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">SERVICIOS MÁS VENDIDOS</p><h2>Distribución y top 10</h2></div><a href="{{ route('services.index') }}">Catálogo →</a></header>@if($serviceMix->isNotEmpty())<div class="finance-chart-layout compact"><div style="width:100px;height:100px;border-radius:50%;background:conic-gradient({{ implode(',', $serviceSegments) }})"></div><div style="display:grid;gap:6px">@foreach($serviceMix as $serviceMixItem)<small><strong>{{ $serviceMixItem['percent'] }}%</strong> {{ $serviceMixItem['name'] }}</small>@endforeach</div></div>@endif<div class="agenda-list">@forelse($services as $service)<div class="agenda-row"><time>{{ number_format($service['quantity'], 0) }} serv.</time><div><strong>{{ $service['name'] }}</strong><span>${{ number_format($service['amount'], 2) }}</span></div></div>@empty<p class="empty-state">No hay servicios vendidos en este periodo.</p>@endforelse</div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">CREPERAS QUE MÁS VENDIERON SERVICIOS</p><h2>Top 10</h2></div></header><div class="agenda-list">@forelse($serviceSellers as $seller)<div class="agenda-row"><time>${{ number_format($seller['amount'], 0) }}</time><div><strong>{{ $seller['name'] }}</strong><span>Ventas de servicios</span></div></div>@empty<p class="empty-state">Sin ventas asignadas a creperas.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">CREPERAS QUE MÁS VENDIERON PRODUCTOS</p><h2>Top 10</h2></div></header><div class="agenda-list">@forelse($productSellers as $seller)<div class="agenda-row"><time>${{ number_format($seller['amount'], 0) }}</time><div><strong>{{ $seller['name'] }}</strong><span>Ventas de productos</span></div></div>@empty<p class="empty-state">Sin ventas de productos asignadas.</p>@endforelse</div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">PRINCIPALES GASTOS</p><h2>Por categoría</h2></div><a href="{{ route('finance.index', ['view' => 'movements', 'type' => 'expense']) }}">Ver gastos →</a></header><div class="agenda-list">@forelse($expenses as $expense)<div class="agenda-row"><time>${{ number_format($expense['amount'], 0) }}</time><div><strong>{{ $expense['name'] }}</strong><span>Gastos del periodo</span></div></div>@empty<p class="empty-state">No hay gastos registrados.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">PEDIDOS DE INVENTARIO</p><h2>Solicitudes recientes</h2></div><a href="{{ route('inventory.requests.index') }}">Ver solicitudes →</a></header><div class="agenda-list">@forelse($inventoryRequests as $inventoryRequest)<div class="agenda-row"><time>{{ $inventoryRequest->created_at?->format('d/m') }}</time><div><strong>{{ $inventoryRequest->code }}</strong><span>{{ $inventoryRequest->sourceLocation?->name ?? 'Inventario' }} · {{ $inventoryRequest->items->count() }} productos</span></div></div>@empty<p class="empty-state">No hay pedidos en este periodo.</p>@endforelse</div></article></section>
</x-layouts.app>
