<x-layouts.app title="Resumen financiero">
    @php
        $productPercent = $totalRevenue > 0 ? round($productRevenue / $totalRevenue * 100) : 0;
        $servicePercent = $totalRevenue > 0 ? 100 - $productPercent : 0;
        $servicePalette = ['#b95070', '#d88ca4', '#8c6b9f', '#6b8fc4', '#4eaa8b', '#c7b07a'];
        $serviceOffset = 0;
        $serviceSegments = [];
        foreach ($serviceMix as $index => $serviceMixItem) {
            $nextOffset = min(100, $serviceOffset + $serviceMixItem['percent']);
            $serviceSegments[] = $servicePalette[$index % count($servicePalette)].' '.$serviceOffset.'% '.$nextOffset.'%';
            $serviceOffset = $nextOffset;
        }
    @endphp
    <section class="page-title"><div><p class="eyebrow">CONTROL FINANCIERO</p><h1>Resumen financiero</h1><p>Ingresos, gastos y saldos del {{ $fromLabel }} al {{ $toLabel }}.</p></div><div class="title-actions"><a class="button button-secondary" href="{{ route('finance.index', ['view' => 'movements', 'from' => $from, 'to' => $to]) }}">Ver movimientos</a><a class="button button-primary" href="{{ route('finance.index', ['view' => 'movements', 'modal' => 'transaction']) }}">+ Agregar movimiento</a></div></section>
    <form method="GET" class="list-filter-bar dashboard-period-filter" aria-label="Periodo del resumen"><input type="hidden" name="view" value="dashboard"><input type="hidden" name="period" value="custom"><div class="dashboard-period-presets" aria-label="Periodos rápidos"><a class="{{ $period === 'today' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'dashboard', 'period' => 'today']) }}">Hoy</a><a class="{{ $period === 'current_month' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'dashboard', 'period' => 'current_month']) }}">Mes en curso</a><a class="{{ $period === 'previous_month' ? 'is-active' : '' }}" href="{{ route('finance.index', ['view' => 'dashboard', 'period' => 'previous_month']) }}">Mes anterior</a></div><label class="date-filter"><span>Desde</span><input name="from" type="date" value="{{ $from }}"></label><label class="date-filter"><span>Hasta</span><input name="to" type="date" value="{{ $to }}"></label><button class="button button-secondary" type="submit">Aplicar rango</button>@if($period === 'custom')<a class="filter-clear" href="{{ route('finance.index', ['view' => 'dashboard']) }}">Restablecer</a>@endif</form>
    <section class="metric-grid"><article class="metric-card"><span>INGRESOS REGISTRADOS</span><strong class="positive">${{ number_format($totalIncome, 2) }}</strong><small class="neutral">{{ number_format($incomeRecordCount) }} registros del periodo</small></article><article class="metric-card"><span>GASTOS REGISTRADOS</span><strong class="negative">${{ number_format($expenseTotal, 2) }}</strong><small class="neutral">{{ number_format($expenseRecordCount) }} egresos del periodo</small></article><article class="metric-card"><span>FLUJO NETO</span><strong class="{{ $netTotal >= 0 ? 'positive' : 'negative' }}">${{ number_format($netTotal, 2) }}</strong><small class="neutral">Ingresos menos gastos</small></article><article class="metric-card"><span>SALDO EN CUENTAS</span><strong>${{ number_format($totalAccountBalance, 2) }}</strong><small class="neutral">Al cierre del {{ $toLabel }}</small></article></section>

    <section class="dashboard-grid" style="margin-top:16px"><article class="surface"><header><div><p class="eyebrow">ORIGEN DE INGRESOS</p><h2>Registro financiero del periodo</h2><p>Se integran movimientos manuales y cobros de tickets.</p></div></header><div class="agenda-list"><div class="agenda-row"><time>Movimientos</time><div><strong>${{ number_format($manualIncome, 2) }}</strong><span>Ingresos registrados directamente</span></div></div><div class="agenda-row"><time>Tickets</time><div><strong>${{ number_format($ticketIncome, 2) }}</strong><span>Cobros confirmados en tickets</span></div></div></div></article><article class="surface"><header><div><p class="eyebrow">INGRESOS POR CUENTA</p><h2>Cómo entró el dinero</h2><p>Clasificado por el tipo de cuenta de destino.</p></div></header><div class="agenda-list"><div class="agenda-row"><time>Efectivo</time><div><strong>${{ number_format($cashIncome, 2) }}</strong><span>Cajas y efectivo</span></div></div><div class="agenda-row"><time>Bancario</time><div><strong>${{ number_format($bankIncome, 2) }}</strong><span>Tarjetas y transferencias</span></div></div><div class="agenda-row"><time>Otros</time><div><strong>${{ number_format($otherIncome, 2) }}</strong><span>Otras cuentas y medios</span></div></div></div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">PRODUCTOS MÁS VENDIDOS</p><h2>Top 10 productos</h2></div><a href="{{ route('products.index') }}">Catálogo →</a></header><div class="agenda-list">@forelse($products as $product)<div class="agenda-row"><time>{{ number_format($product['quantity'], 0) }} u.</time><div><strong>{{ $product['name'] }}</strong><span>${{ number_format($product['amount'], 2) }}</span></div></div>@empty<p class="empty-state">No hay ventas de productos en este periodo.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">SERVICIOS MÁS VENDIDOS</p><h2>Distribución y top 10</h2></div><a href="{{ route('services.index') }}">Catálogo →</a></header>@if($serviceMix->isNotEmpty())<div class="finance-chart-layout compact"><div style="width:100px;height:100px;border-radius:50%;background:conic-gradient({{ implode(',', $serviceSegments) }})"></div><div style="display:grid;gap:6px">@foreach($serviceMix as $serviceMixItem)<small><strong>{{ $serviceMixItem['percent'] }}%</strong> {{ $serviceMixItem['name'] }}</small>@endforeach</div></div>@endif<div class="agenda-list">@forelse($services as $service)<div class="agenda-row"><time>{{ number_format($service['quantity'], 0) }} serv.</time><div><strong>{{ $service['name'] }}</strong><span>${{ number_format($service['amount'], 2) }}</span></div></div>@empty<p class="empty-state">No hay servicios vendidos en este periodo.</p>@endforelse</div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">CREPERAS QUE MÁS VENDIERON SERVICIOS</p><h2>Top 10</h2></div></header><div class="agenda-list">@forelse($serviceSellers as $seller)<div class="agenda-row"><time>${{ number_format($seller['amount'], 0) }}</time><div><strong>{{ $seller['name'] }}</strong><span>Ventas de servicios</span></div></div>@empty<p class="empty-state">Sin ventas asignadas a creperas.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">CREPERAS QUE MÁS VENDIERON PRODUCTOS</p><h2>Top 10</h2></div></header><div class="agenda-list">@forelse($productSellers as $seller)<div class="agenda-row"><time>${{ number_format($seller['amount'], 0) }}</time><div><strong>{{ $seller['name'] }}</strong><span>Ventas de productos</span></div></div>@empty<p class="empty-state">Sin ventas de productos asignadas.</p>@endforelse</div></article></section>

    <section class="dashboard-grid"><article class="surface"><header><div><p class="eyebrow">PRINCIPALES GASTOS</p><h2>Por categoría</h2></div><a href="{{ route('finance.index', ['view' => 'movements', 'type' => 'expense']) }}">Ver gastos →</a></header><div class="agenda-list">@forelse($expenses as $expense)<div class="agenda-row"><time>${{ number_format($expense['amount'], 0) }}</time><div><strong>{{ $expense['name'] }}</strong><span>Gastos del periodo</span></div></div>@empty<p class="empty-state">No hay gastos registrados.</p>@endforelse</div></article><article class="surface"><header><div><p class="eyebrow">PEDIDOS DE INVENTARIO</p><h2>Solicitudes recientes</h2></div><a href="{{ route('inventory.requests.index') }}">Ver solicitudes →</a></header><div class="agenda-list">@forelse($inventoryRequests as $inventoryRequest)<div class="agenda-row"><time>{{ $inventoryRequest->created_at?->format('d/m') }}</time><div><strong>{{ $inventoryRequest->code }}</strong><span>{{ $inventoryRequest->sourceLocation?->name ?? 'Inventario' }} · {{ $inventoryRequest->items->count() }} productos</span></div></div>@empty<p class="empty-state">No hay pedidos en este periodo.</p>@endforelse</div></article></section>
</x-layouts.app>
