<x-layouts.app :title="$customer->exists ? 'Editar clienta' : 'Nueva clienta'">
    <section class="page-title"><div><p class="eyebrow">CRM · CLIENTAS</p><h1>{{ $customer->exists ? 'Editar clienta' : 'Nueva clienta' }}</h1><p>Datos que estarán disponibles en su ticket e historial.</p></div><a class="button button-secondary" href="{{ route('customers.index') }}">Cancelar</a></section>
    <form class="surface detail-form" method="POST" action="{{ $customer->exists ? route('customers.update', $customer) : route('customers.store') }}">@csrf @if($customer->exists) @method('PUT') @endif
        <div class="form-section"><h2>Datos de clienta</h2><p>La información básica para identificarla fácilmente.</p><div class="field-grid"><label><span>Nombre</span><input name="first_name" value="{{ old('first_name', $customer->first_name) }}" required>@error('first_name')<small>{{ $message }}</small>@enderror</label><label><span>Apellidos</span><input name="last_name" value="{{ old('last_name', $customer->last_name) }}" required>@error('last_name')<small>{{ $message }}</small>@enderror</label><label><span>Teléfono</span><input name="phone" value="{{ old('phone', $customer->phone) }}" placeholder="999 000 0000"></label><label><span>WhatsApp</span><input name="whatsapp" value="{{ old('whatsapp', $customer->whatsapp) }}" placeholder="999 000 0000"></label><label><span>Correo</span><input name="email" type="email" value="{{ old('email', $customer->email) }}" placeholder="clienta@correo.com">@error('email')<small>{{ $message }}</small>@enderror</label><label><span>Fecha de nacimiento</span><input name="birthday" type="date" value="{{ old('birthday', optional($customer->birthday)->format('Y-m-d')) }}"></label><label><span>Estatus</span><select name="status"><option value="active" @selected(old('status', $customer->status ?: 'active') === 'active')>Activa</option><option value="inactive" @selected(old('status', $customer->status) === 'inactive')>Inactiva</option></select></label></div></div>
        <div class="form-section"><h2>Notas internas</h2><p>Información útil para el equipo; no se mostrará a la clienta.</p><label class="full-field"><span>Observaciones</span><textarea name="notes" rows="4" placeholder="Preferencias, alergias u observaciones…">{{ old('notes', $customer->notes) }}</textarea></label></div>
        <footer class="form-footer">@if($customer->exists)<button class="button button-secondary" type="submit" form="archive-customer">Archivar clienta</button>@endif<a href="{{ route('customers.index') }}">Cancelar</a><button class="button button-primary" type="submit">{{ $customer->exists ? 'Guardar cambios' : 'Crear clienta' }}</button></footer>
    </form>
    @if($customer->exists)<form id="archive-customer" method="POST" action="{{ route('customers.destroy', $customer) }}" onsubmit="return confirm('¿Archivar esta clienta? Su historial se conservará.')">@csrf @method('DELETE')</form>@endif
</x-layouts.app>
