<x-layouts.app :title="$promotion->exists ? 'Editar promo' : 'Nueva promo'">
    <section class="page-title"><div><p class="eyebrow">PROMOS</p><h1>{{ $promotion->exists ? 'Editar promoción' : 'Nueva promoción' }}</h1><p>Configura una regla clara; el sistema calcula el descuento antes de cobrar el ticket.</p></div><a class="button button-secondary" href="{{ route('promotions.index') }}">Volver</a></section>
    <form method="POST" action="{{ $promotion->exists ? route('promotions.update', $promotion) : route('promotions.store') }}" class="promotion-form">
        @csrf @if($promotion->exists) @method('PUT') @endif
        <section class="surface form-section"><header><div><p class="eyebrow">TIPO</p><h2>Cómo funciona</h2></div></header><div class="form-grid"><label><span>Nombre interno</span><input name="name" value="{{ old('name', $promotion->name) }}" placeholder="Ej. Corte + producto" required></label><label><span>Estatus</span><select name="status"><option value="active" @selected(old('status', $promotion->status) === 'active')>Activa</option><option value="inactive" @selected(old('status', $promotion->status) === 'inactive')>Inactiva</option></select></label><label><span>Forma de activación</span><select name="method" id="promo-method"><option value="automatic" @selected(old('method', $promotion->method) === 'automatic')>Automática</option><option value="code" @selected(old('method', $promotion->method) === 'code')>Con código</option></select></label><label data-code-field><span>Código</span><input name="code" value="{{ old('code', $promotion->code) }}" placeholder="CREPE10"><small>La clienta lo captura en recepción.</small></label></div></section>
        <section class="surface form-section"><header><div><p class="eyebrow">REGLA</p><h2>Beneficio de la promoción</h2></div></header><div class="form-grid"><label><span>Tipo de promoción</span><select name="type" id="promo-type"><option value="order" @selected(old('type', $promotion->type) === 'order')>Descuento al total del ticket</option><option value="items" @selected(old('type', $promotion->type) === 'items')>Descuento en productos o servicios</option><option value="buy_x_get_y" @selected(old('type', $promotion->type) === 'buy_x_get_y')>Compra X y recibe Y gratis</option></select></label><label data-value-field><span>Valor</span><div class="inline-fields"><select name="value_type"><option value="percentage" @selected(old('value_type', $promotion->value_type) === 'percentage')>Porcentaje</option><option value="fixed" @selected(old('value_type', $promotion->value_type) === 'fixed')>Monto fijo</option></select><input type="number" name="value" min="0" step=".01" value="{{ old('value', $promotion->value) }}" placeholder="10"></div></label><label><span>Mínimo de compra (opcional)</span><input type="number" name="minimum_amount" min="0" step=".01" value="{{ old('minimum_amount', $promotion->minimum_amount) }}" placeholder="$0.00"></label><label><span>Límite de usos (opcional)</span><input type="number" name="usage_limit" min="1" step="1" value="{{ old('usage_limit', $promotion->usage_limit) }}" placeholder="Sin límite"></label></div></section>
        <section class="surface form-section" data-target-section><header><div><p class="eyebrow">APLICA A</p><h2>Productos y servicios participantes</h2><p>Color Bar se mantiene fuera de estas promociones para no mezclar inventarios.</p></div></header><div class="form-grid"><label><span>Productos</span><select name="target_product_ids[]" multiple size="6">@foreach($products as $product)<option value="{{ $product->id }}" @selected(in_array($product->id, old('target_product_ids', $promotion->target['product_ids'] ?? [])))>{{ $product->name }}</option>@endforeach</select><small>Usa ⌘/Ctrl para seleccionar varios.</small></label><label><span>Servicios</span><select name="target_service_ids[]" multiple size="6">@foreach($services as $service)<option value="{{ $service->id }}" @selected(in_array($service->id, old('target_service_ids', $promotion->target['service_ids'] ?? [])))>{{ $service->name }}</option>@endforeach</select></label></div></section>
        <section class="surface form-section" data-reward-section><header><div><p class="eyebrow">REGALO</p><h2>Compra X y recibe Y</h2><p>El regalo queda visible en el ticket. Si es producto, se descuenta del inventario de Recepción.</p></div></header><div class="form-grid"><label><span>Cantidad que compra</span><input type="number" name="buy_quantity" min="1" value="{{ old('buy_quantity', $promotion->buy_quantity ?: 2) }}"></label><label><span>Cantidad de regalo</span><input type="number" name="reward_quantity" min="1" value="{{ old('reward_quantity', $promotion->reward_quantity ?: 1) }}"></label><label><span>Tipo de regalo</span><select name="reward_type" id="reward-type"><option value="product">Producto</option><option value="service">Servicio</option></select></label><label><span>Regalo</span><select name="reward_id" id="reward-id"><option value="">Selecciona...</option>@foreach($products as $product) @foreach($product->variants as $variant)<option data-reward-kind="product" value="{{ $variant->id }}">Producto · {{ $product->name }} · {{ $variant->name }}</option>@endforeach @endforeach @foreach($services as $service)<option data-reward-kind="service" value="{{ $service->id }}">Servicio · {{ $service->name }}</option>@endforeach</select></label></div></section>
        <section class="surface form-section"><header><div><p class="eyebrow">VIGENCIA</p><h2>Fechas y límites</h2></div></header><div class="form-grid"><label><span>Comienza</span><input type="datetime-local" name="starts_at" value="{{ old('starts_at', $promotion->starts_at?->format('Y-m-d\\TH:i')) }}"></label><label><span>Termina (opcional)</span><input type="datetime-local" name="ends_at" value="{{ old('ends_at', $promotion->ends_at?->format('Y-m-d\\TH:i')) }}"></label><label class="check-field"><input type="checkbox" name="one_per_customer" value="1" @checked(old('one_per_customer', $promotion->one_per_customer))><span>Una vez por clienta</span></label></div><footer><button class="button button-primary" type="submit">{{ $promotion->exists ? 'Guardar cambios' : 'Crear promoción' }}</button></footer></section>
    </form>
    <script>
        const type = document.getElementById('promo-type'); const valueField = document.querySelector('[data-value-field]'); const targetSection = document.querySelector('[data-target-section]'); const rewardSection = document.querySelector('[data-reward-section]'); const method = document.getElementById('promo-method'); const codeField = document.querySelector('[data-code-field]'); const rewardType = document.getElementById('reward-type'); const rewardId = document.getElementById('reward-id');
        const update = () => { const isGift = type.value === 'buy_x_get_y'; valueField.hidden = isGift; targetSection.hidden = type.value === 'order'; rewardSection.hidden = !isGift; codeField.hidden = method.value !== 'code'; [...rewardId.options].forEach(option => { option.hidden = option.value && option.dataset.rewardKind !== rewardType.value; }); if (rewardId.selectedOptions[0]?.hidden) rewardId.value = ''; }; type.addEventListener('change', update); method.addEventListener('change', update); rewardType.addEventListener('change', update); update();
    </script>
</x-layouts.app>
