<x-layouts.app title="Checks">
    <section class="page-title attendance-title"><div><p class="eyebrow">ASISTENCIA</p><h1>Checks</h1><p>Registro rápido de entrada y salida, con seguimiento de incidencias para nómina.</p></div>@if($canManageIncidents)<a class="button button-secondary" href="{{ route('settings.edit') }}">Configurar horarios</a>@endif</section>
    <section class="attendance-layout">
        <article class="surface attendance-kiosk">
            <header><p class="eyebrow">REGISTRO DEL DÍA</p><h2>Ingresa tu código</h2><p>Marca entrada o salida con los 4 dígitos asignados.</p></header>
            <form method="POST" action="{{ route('attendance.register') }}" data-check-form>@csrf
                <input class="attendance-pin" data-check-pin name="pin" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="off" readonly required aria-label="Código de cuatro dígitos">
                @error('pin')<p class="form-error">{{ $message }}</p>@enderror
                <div class="attendance-keypad" aria-label="Teclado numérico">@foreach([1,2,3,4,5,6,7,8,9] as $digit)<button type="button" data-key="{{ $digit }}">{{ $digit }}</button>@endforeach<button type="button" class="attendance-key-clear" data-key="clear">Limpiar</button><button type="button" data-key="0">0</button><button type="button" class="attendance-key-delete" data-key="delete" aria-label="Borrar último dígito">←</button></div>
                <button class="button button-primary attendance-submit" type="submit">Registrar</button>
            </form>
        </article>
        <article class="surface attendance-guide"><p class="eyebrow">REGLAS ACTIVAS</p><h2>Asistencia y nómina</h2><dl><div><dt>Entrada</dt><dd>Se registra según el horario configurado.</dd></div><div><dt>Retardos</dt><dd>Se aplican automáticamente en la nómina del periodo.</dd></div><div><dt>Faltas</dt><dd>Primero deben resolverse en Incidencias.</dd></div></dl></article>
    </section>
    @if($canManageIncidents)<section class="surface attendance-incidents" id="incidencias">
        <header class="attendance-incidents-head"><div><p class="eyebrow">INCIDENCIAS</p><h2>Faltas y registros incompletos</h2><p>Una nómina no podrá generarse mientras haya incidencias pendientes dentro de su periodo.</p></div><form method="GET" class="attendance-range"><label><span>Desde</span><input type="date" name="from" value="{{ $from->toDateString() }}"></label><label><span>Hasta</span><input type="date" name="to" value="{{ $to->toDateString() }}"></label><button class="button button-secondary" type="submit">Filtrar</button></form></header>
        <div class="attendance-incident-list">@forelse($incidents as $incident)<article class="attendance-incident {{ $incident->status === 'pending' ? 'is-pending' : 'is-resolved' }}"><div class="attendance-incident-summary"><span class="attendance-date">{{ $incident->work_date->translatedFormat('D d M') }}</span><div><strong>{{ $incident->employee->full_name }}</strong><small>{{ $incident->type === 'absence' ? 'Sin entrada ni salida registradas' : 'Entrada sin salida registrada' }} · {{ $incident->employee->position }}</small></div><span class="status-badge">{{ $incident->status === 'pending' ? 'Pendiente' : ($incident->resolution === 'day_discount' ? 'Descuento de día' : 'Falta justificada') }}</span></div>@if($incident->status === 'pending')<form method="POST" action="{{ route('attendance.incidents.resolve', $incident) }}" class="attendance-incident-form">@csrf @method('PUT')<label><span>Resolución</span><select name="resolution" required><option value="">Selecciona una opción</option><option value="day_discount">Descuento de día</option><option value="justified_absence">Falta justificada</option></select></label><label><span>Motivo</span><input name="reason" maxlength="1000" placeholder="Ej. Incapacidad médica" required></label><button class="button button-primary" type="submit">Atender incidencia</button></form>@else<div class="attendance-resolution"><strong>{{ $incident->reason }}</strong><span>{{ $incident->resolution === 'day_discount' ? 'Se calculará el descuento proporcional al generar la nómina.' : 'No genera descuento.' }}</span></div>@endif</article>@empty<p class="empty-state">No hay incidencias en este periodo.</p>@endforelse</div>
    </section>@endif
    <script>
        (() => { const form = document.querySelector('[data-check-form]'); const input = document.querySelector('[data-check-pin]'); if (!form || !input) return; document.querySelectorAll('[data-key]').forEach((button) => button.addEventListener('click', () => { const key = button.dataset.key; if (key === 'clear') input.value = ''; else if (key === 'delete') input.value = input.value.slice(0, -1); else if (input.value.length < 4) input.value += key; })); form.addEventListener('submit', (event) => { if (input.value.length !== 4) { event.preventDefault(); input.focus(); } }); })();
    </script>
</x-layouts.app>
